website/models.py
from . import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class Computer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    description = db.Column(db.String(1000))
    # Other fields as necessary
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    first_name = db.Column(db.String(150))
    products = db.relationship('Product', backref='user', lazy=True)
    computers = db.relationship('Computer', backref='user', lazy=True)
class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    description = db.Column(db.String(1000))
    image_filename = db.Column(db.String(100))
    price = db.Column(db.Float)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'asfkoaskfl;kasflksl'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db 
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if user.check_password(password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.main'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name)
            new_user.set_password(password1)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.main'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from . import db
from .models import User, Product, Computer


views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])


@views.route('/main')
def main():
    return render_template("index.html", user=current_user)
@views.route('/prod')
def prod():
    return render_template("prod.html", user=current_user)

@views.route('/add-product', methods=['POST'])
@login_required
def add_product():
    product_data = request.form
    new_product = Product(
        image_filename=product_data.get('image_filename'),
        name=product_data.get('name'),
        description=product_data.get('description'),
        price=product_data.get('price'),
        user_id=current_user.id
    )
    db.session.add(new_product)
    db.session.commit()
    #flash('Product added to profile!', category='success')
    return redirect(url_for('views.profile'))

@views.route('/hello')
def hello():
    return "<p>hello</p>"





@views.route('/delete-product/<int:product_id>', methods=['POST'])
@login_required
def delete_product(product_id):
    product = Product.query.get_or_404(product_id)
    if product.user_id != current_user.id:
        #flash('You do not have permission to delete this product.', category='error')
        return redirect(url_for('views.profile'))
    db.session.delete(product)
    db.session.commit()
    #flash('Product has been deleted!', category='success')
    return redirect(url_for('views.profile'))

@views.route('/add_computer/<int:computer_id>')
@login_required
def add_computer(computer_id):
    computer = Computer.query.get(computer_id)
    if computer and computer.user_id is None:  # Check if computer is not already added by another user
        computer.user_id = current_user.id
        db.session.commit()
        #flash('Computer added to your list', 'success')
    else:
        flash('Computer not found or already added by someone else', 'error')
    return redirect(url_for('views.pc'))

@views.route('/my_computers')
@login_required
def my_computers():
    user_computers = Computer.query.filter_by(user_id=current_user.id).all()
    return render_template('my_computers.html', computers=user_computers, user=current_user)

@views.route('/pc')
def pc():
    # Display a list of all computers. Modify query as needed.
    all_computers = Computer.query.all()
    return render_template('pc.html', computers=all_computers, user=current_user)

@views.route('/pc2')
def pc2():
    return render_template("pc2.html", user=current_user)

@views.route('/pc3')
def pc3():
    return render_template("pc3.html", user=current_user)

@views.route('/pc4')
def pc4():
    return render_template("pc4.html", user=current_user)

@views.route('/pc5')
def pc5():
    return render_template("pc5.html", user=current_user)

@views.route('/pc6')
def pc6():
    return render_template("pc6.html", user=current_user)

@views.route('/user_page')
@login_required
def user_page():
    return render_template('user_page.html', user=current_user)


@views.route('/profile')
@login_required
def profile():
    user_products = Product.query.filter_by(user_id=current_user.id).all()
    user_computers = Computer.query.filter_by(user_id=current_user.id).all()  # Added line to fetch user computers
    return render_template("profile.html", user=current_user, products=user_products, computers=user_computers)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
      <link rel="icon" href="favicon.ico">
      <link rel="stylesheet" href= "{{ url_for('static', filename='css/styles.css')}}">
      <link rel="stylesheet" href= "{{ url_for('static', filename='css/style.css')}}">
      <link rel="stylesheet" href= "{{ url_for('static', filename='css/swiper-bundle.min.css')}}">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/prod.css')}}">
      <link href="fontawesome-free-6.4.0-web/css/fontawesome.css" rel="stylesheet">
      <link href="fontawesome-free-6.4.0-web/css/brands.css" rel="stylesheet">
      <link href="fontawesome-free-6.4.0-web/css/solid.css" rel="stylesheet">
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.jpg') }}" type="image/jpeg">
      <title>{% block title %}Home{% endblock %}</title>
</head>
<header class="p-3 text-bg-blue" style="background-color: cornflowerblue!important">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/main" class="nav-link px-2 text-white">Home</a></li>
        <li><a href="prod" class="nav-link px-2 text-white">Our Products</a></li>
        {% if user.is_authenticated %}
        <a class="nav-link px-2 text-white" id="logout" href="/logout">Logout</a>
        {% else %}
        <a class="nav-link px-2 text-white" id="login" href="/login">Login</a>
        <a class="nav-link px-2 text-white" id="signUp" href="/sign-up">Sign Up</a>
        {% endif %}
      </ul>
      <div class="text-end">
        {% if user.is_authenticated %}
        <a href="/profile" type="button" class="btnn btn btn-warning"><i class="fa-solid fa-cart-shopping" style="color: #000000;"></i></a>
        {% else %}
        <a href="/sign-up" type="button" class="btnn btn btn-warning"><i class="fa-solid fa-cart-shopping" style="color: #000000;"></i></a>
        {%endif%}
        <a href="/user_page" type="button" class="btnn btn"><i class="fa-sharp fa-solid fa-user"></i></a>
      </div>
    </div>
  </div>
</header>
  <body>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://kit.fontawesome.com/4ebea0040a.js" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
    <h1 align="center">Notes</h1>
    <ul class="list-group list-group-flush" id="notes">
      {% for note in user.notes %}
      <li class="list-group-item">
        {{ note.data }}
        <button type="button" class="close" onClick="deleteNote({{ note.id }})">
          <span aria-hidden="true">&times;</span>
        </button>
      </li>
      {% endfor %}
    </ul>
    <form method="POST">
      <textarea name="note" id="note" class="form-control"></textarea>
      <br />
      <div align="center">
        <button type="submit" class="btn btn-primary">Add Note</button>
      </div>
    </form>
    {% endblock %}

website/templates/pc2.html
{% extends "base_pc.html" %}

{% block title %}
    Твоё сердце будет разбито
{% endblock %}

{% block body %}
    <h2 class="title">Твоё сердце будет разбито</h2>
    <div class="container">
        <div class="product">
            <div class="row align-items-start">
                <div class="col-md-6">
                    <form action="{{ url_for('views.add_product') }}" method="post">
                        <img src="{{ url_for('static', filename='img/img_2.jpg') }}" alt="" class="product-img img-fluid">
                </div>
                <div class="col-md-6">
                    <div class="product-text">
                        <hr class="product-line">
                        <p class="description">
                            Я вижу его каждый день в окне дома напротив. Он самый крутой парень в моей новой школе.
                            Красавчик, от которого все без ума. Опасный одиночка, который меня не замечает.
                            Однажды он спас меня от одноклассниц, решивших превратить мою жизнь в ад.
                            Cказал всем, что я его девушка, и при всех украл мой первый поцелуй!
                            Теперь никто не смеет тронуть меня, потому что не рискнет с ним связываться.
                            Взамен я должна буду делать все, что он скажет. Я терпеть его не могу, но вынуждена подчиниться,
                            если хочу закончить школу без проблем. Чье сердце будет разбито? Мое или его?
                        </p>
                        <p class="price">3831₸</p>
                        <input type="hidden" name="name" value="Твоё сердце будет разбито">
                        <input type="hidden" name="description" value="
                            Издательство	Clever,
                            ISBN	978-5-00211-133-6,
                            Переплет	твердый переплет
                            ">
                        <input type="hidden" name="price" value="3831">
                        <input type="hidden" name="image_filename"
                            value="{{ url_for('static', filename='img/img_2.jpg') }}">
                        <hr class="product-line">
                        {% if user.is_authenticated %}
                            <button type="submit" class="product-button">
                                Add to profile
                            </button>
                        {% else %}
                            <a href="/sign-up" type="button" class="product-button">Add to Profile</a>
                        {% endif %}
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/pc3.html
{% extends "base_pc.html" %}

{% block title %}
    Убийство Роджера Экройда
{% endblock %}

{% block body %}
    <h2 class="title">Убийство Роджера Экройда</h2>
    <div class="container">
        <div class="product">
            <div class="row align-items-start">
                <div class="col-md-6">
                    <form action="{{ url_for('views.add_product') }}" method="post">
                        <img src="{{ url_for('static', filename='img/img_3.jpg') }}" alt="" class="product-img img-fluid">
                </div>
                <div class="col-md-6">
                    <div class="product-text">
                        <hr class="product-line">
                        <p class="description">
                            Поначалу убийство эсквайра Роджера Экройда не казалось полиции загадочным —
                            все указывало на виновность пасынка убитого. Но иначе считает Эркюль Пуаро,
                            который недавно переехал в эти места, в очередной раз решив уйти на покой.
                            Он начинает расследование, имея вокруг множество подозреваемых — родственников
                            и знакомых эсквайра, каждый из которых был заинтересован в его смерти.
                            Повествование ведется от имени доктора Шеппарда, последнего, кто видел Экройда живым...
                        </p>
                        <p class="price">2991₸</p>
                        <input type="hidden" name="name" value="Убийство Роджера Экройда">
                        <input type="hidden" name="description" value="
                                Издательство	Эксмо,
                                ISBN	978-5-04-101008-9,
                                Переплет	твердый переплет
                            ">
                        <input type="hidden" name="price" value="2991">
                        <input type="hidden" name="image_filename"
                            value="{{ url_for('static', filename='img/img_3.jpg') }}">
                        <hr class="product-line">
                        {% if user.is_authenticated %}
                            <button type="submit" class="product-button">
                                Add to profile
                            </button>
                        {% else %}
                            <a href="/sign-up" type="button" class="product-button">Add to Profile</a>
                        {% endif %}
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/pc4.html
{% extends "base_pc.html" %}

{% block title %}
    Токийский гуль
{% endblock %}

{% block body %}
    <h2 class="title">Токийский гуль</h2>
    <div class="container">
        <div class="product">
            <div class="row align-items-start">
                <div class="col-md-6">
                    <form action="{{ url_for('views.add_product') }}" method="post">
                        <img src="{{ url_for('static', filename='img/img_4.jpg') }}" alt="" class="product-img img-fluid">
                </div>
                <div class="col-md-6">
                    <div class="product-text">
                        <hr class="product-line">
                        <p class="description">
                            Прошлое хранит свои собственные тайны... Потеряв родителей, юные Тока и Аято Кирисима
                            всячески стараются утвердиться в двадцатом районе, ведь среди гулей непозволительно быть
                            слабым. Понимает это и Кадзуити Бандзё – гуль, следующий строгим правилам и старающийся
                            избегать лишних неприятностей. Вот только он влюблен в ненасытную Ридзэ Камисиро, а беды
                            идут за ней по пятам. Жизнь кипит и в мире людей: студентка Академии ККГ Акира Мадо
                            сталкивается с мальчиком, жаждущим отомстить чудовищу-людоеду за смерть отца,
                            а Кэн Канэки пытается ужиться в неприветливой приемной семье, совершенно не подозревая,
                            что ждет его в будущем... В эту книгу вошло шесть новых историй из вселенной
                            «Токийского гуля», действие которых разворачивается до основных событий манги.
                        </p>
                        <p class="price">3703₸</p>
                        <input type="hidden" name="name" value="Токийский гуль">
                        <input type="hidden" name="description" value="
                            Автор Исида С., Товада С.,
                            ISBN 978-5-389-17318-7,
                            Жанр Манга
                            ">
                        <input type="hidden" name="price" value="3703">
                        <input type="hidden" name="image_filename"
                            value="{{ url_for('static', filename='img/img_4.jpg') }}">
                        <hr class="product-line">
                        {% if user.is_authenticated %}
                            <button type="submit" class="product-button">
                                Add to profile
                            </button>
                        {% else %}
                            <a href="/sign-up" type="button" class="product-button">Add to Profile</a>
                        {% endif %}
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/pc5.html
{% extends "base_pc.html" %}

{% block title %}
    Убийца Гоблинов
{% endblock %}

{% block body %}
    <h2 class="title">Убийца Гоблинов</h2>
    <div class="container">
        <div class="product">
            <div class="row align-items-start">
                <div class="col-md-6">
                    <form action="{{ url_for('views.add_product') }}" method="post">
                        <img src="{{ url_for('static', filename='img/img_5.jpg') }}" alt="" class="product-img img-fluid">
                </div>
                <div class="col-md-6">
                    <div class="product-text">
                        <hr class="product-line">
                        <p class="description">
                            Ходят слухи, что в гильдии Города на Пограничье обитает человек, который достиг серебряного
                            ранга, убивая одних лишь гоблинов. Жрица становится авантюристкой и вступает в свою первую
                            группу, но тут же оказывается в смертельной опасности. Её спасает человек, которого прозвали
                            Убийцей Гоблинов. Он истребляет гоблинов, не выбирая средств и не останавливаясь перед
                            трудностями. Рядом с ним оказываются Жрица, которая ходит с ним на все задания,
                            Регистраторша, искренне благодарная авантюристу за всё, и Пастушка, вечно ждущая его дома.
                            Более того, слухи об Убийце Гоблинов доносятся до некой эльфийки. Она приходит к мужчине и
                            предлагает ему новое задание. Долгожданное издание безумно популярной веб-новеллы!
                            Тёмное фэнтези от Кумо Кагю и Нобору Каннацуки!
                        </p>
                        <p class="price">6160₸</p>
                        <input type="hidden" name="name" value="Убийца Гоблинов">
                        <input type="hidden" name="description" value="
                            Автор Кагю К.,
                            ISBN 978-5-907014-85-5,
                            Жанр Манга
                            ">
                        <input type="hidden" name="price" value="6160">
                        <input type="hidden" name="image_filename"
                            value="{{ url_for('static', filename='img/img_5.jpg') }}">
                        <hr class="product-line">
                        {% if user.is_authenticated %}
                            <button type="submit" class="product-button">
                                Add to profile
                            </button>
                        {% else %}
                            <a href="/sign-up" type="button" class="product-button">Add to Profile</a>
                        {% endif %}
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/pc6.html
{% extends "base_pc.html" %}

{% block title %}
    Судьба/Истоки
{% endblock %}

{% block body %}
    <h2 class="title">Судьба/Истоки</h2>
    <div class="container">
        <div class="product">
            <div class="row align-items-start">
                <div class="col-md-6">
                    <form action="{{ url_for('views.add_product') }}" method="post">
                        <img src="{{ url_for('static', filename='img/img_6.jpg') }}" alt="" class="product-img img-fluid">
                </div>
                <div class="col-md-6">
                    <div class="product-text">
                        <hr class="product-line">
                        <p class="description">
                            Вот уже две сотни лет в японском городе Фуюки втайне от обычных граждан проводится
                            состязание между магами, названное Битвой за Святой Грааль. Желая получить Чашу,
                            исполняющую желания, семеро призывают в слуги величайших героев прошлого и сталкиваются
                            в кровавом сражении… Fate/Zero рассказывает о четвертой Битве за Святой Грааль, которая
                            произошла за десять лет до событий культовой игры Fate/stay night. Все знают, что именно
                            катастрофа четвертой Битвы привела к преждевременному началу пятой. Но что же там произошло?
                            Известный сценарист Гэн Уробути, непревзойденный мастер остросюжетного триллера,
                            приподнимает завесу над темными тайнами прошлого…
                        </p>
                        <p class="price">4920₸</p>
                        <input type="hidden" name="name" value="Судьба/Истоки">
                        <input type="hidden" name="description" value="
                            Автор Уробути Г.,
                            ISBN 978-5-91996-313-4,
                            Жанр Манга
                            ">
                        <input type="hidden" name="price" value="4920">
                        <input type="hidden" name="image_filename"
                            value="{{ url_for('static', filename='img/img_6.jpg') }}">
                        <hr class="product-line">
                        {% if user.is_authenticated %}
                            <button type="submit" class="product-button">
                                Add to profile
                            </button>
                        {% else %}
                            <a href="/sign-up" type="button" class="product-button">Add to Profile</a>
                        {% endif %}
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="icon" href="favicon.ico">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/swiper-bundle.min.css')}}">
    <link href="fontawesome-free-6.4.0-web/css/fontawesome.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css')}}">
    <link href="fontawesome-free-6.4.0-web/css/brands.css" rel="stylesheet">
    <link href="fontawesome-free-6.4.0-web/css/solid.css" rel="stylesheet">

</head>
<header class="p-3 text-bg-blue" style="background-color: cornflowerblue">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/main" class="nav-link px-2 text-white">Home</a></li>
                <li><a href="prod" class="nav-link px-2 text-white">Our Products</a></li>
                {% if user.is_authenticated %}
                <a class="nav-link px-2 text-white" id="logout" href="/logout">Logout</a>
                {% else %}
                <a class="nav-link px-2 text-white" id="login" href="/login">Login</a>
                <a class="nav-link px-2 text-white" id="signUp" href="/sign-up">Sign Up</a>
                {% endif %}
            </ul>
            <div class="text-end">
                {% if user.is_authenticated %}
                <a href="/profile" type="button" class="btnn btn btn-warning"><i class="fa-solid fa-cart-shopping"
                        style="color: #000000;"></i></a>
                {% else %}
                <a href="/sign-up" type="button" class="btnn btn btn-warning"><i class="fa-solid fa-cart-shopping"
                        style="color: #000000;"></i></a>
                {%endif%}
                <a  href="user_page" type="button" class="btnn btn"><i class="fa-sharp fa-solid fa-user"></i></a>
            </div>
        </div>
    </div>
</header>

<body>
    {% block content %}
    <div class="product-container">
        {% for product in products %}
        <div class="product-card">
            <div class="main">
                <div class="container">
                    <div class="row align-items-start">
                        <div class="col">
                            <img src="{{product.image_filename}}" alt="{{ product.name }}" class="product-img">
                            <div class="product-text">
                                <h3>{{ product.name }}</h3>
                            </div>
                            <hr class="product-line">
                            <p class="description">{{ product.description }}</p>
                            <p class="price">{{ product.price }}₸</p>
                            <form action="{{ url_for('views.delete_product', product_id=product.id) }}" method="post">
                                <button class="product-button" type="submit">Delete</button>
                            </form>
                        </div>
                        {% else %}
                        <p style="text-align: center; margin-top: 100px">No products found in your profile.</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/4ebea0040a.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/4ebea0040a.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>